### PR TITLE
Fix plugin to work with new version of GitExtensions (2.48.03)

### PR DESCRIPTION
**Pull request by pmiossec**
Should fix https://github.com/gitextensions/gitextensions/issues/2735

### CODE REVIEW

**Comment by pmiossec** [comment]
@spraints Can you merge this PR or give me the rights on this repository? 
I also would like to do a release, so giving the right should be better...

**Comment by spraints** [comment]
> give me the rights on this repository?

:+1: you should be able to merge now.

**Comment by pmiossec** [comment]
>you should be able to merge now.

In fact, no :( 
I just saw, when I wanted to merge, that the `git-tfs` group just give `read` write on the repositories...

**Comment by spraints** [comment]
D'oh. Sorry about that. It should be fixed now.

**Comment by pmiossec** [comment]
Thanks!

**Pull request merged**
